import IndividualIcon from "~/icons/individual.astro"
import OnlineIcon from "~/icons/online.astro"
import ParejaIcon from "~/icons/pareja2.astro"
import PsiconutricionIcon from "~/icons/psiconutricion.astro"

export const servicios = {
  presencial: {
    nombre: "Terapia Individual",
    precio: "70€",
    duracion: "55 minutos",
    link: "/psicologo-barcelona/",
    icon: IndividualIcon,
    target: "Adultos y Adolescentes",
    descripcion:
      "La terapia psicológica presencial es para ti si sufres algún problema emocional o psicológico y quieres superarlo para sentirte mejor.",
    problemas: [
      "Ansiedad",
      "Depresión o Tristeza",
      "Autoestima",
      "Miedos",
      "Estrés y Burnout",
      "Duelos",
      "Gestión de emociones",
      "Trauma",
      "Crecimiento personal",
      "Mobbing (Acoso Laboral)",
      "Ansiedad Social",
      "Dudas patológicas",
      "Crisis",
      "Timidez",
      "Toma de decisiones",
      "Fobias",
      "Ataques de pánico",
      "Inseguridades",
      "Ansiedad Social",
      "Crecimiento personal",
      "Autoconocimiento",
      "Habilidades Sociales",
      "Obsesiones",
      "Autolesiones",
      "Intentos de suicidio",
      "Rituales",
      "Rumiación",
      "Ataques de pánico",
      "Ataques de ansiedad",
      "Compulsiones",
      "Agorafobia",
      "Hipocondría",
      "TOC, TAG, TLP",
      "Trastornos de personalidad",
      "Problemas de alimentación",
      "Bullying",
      "Imagen corporal",
      "Sexualidad",
      "Dismorfia corporal",
      "Baja líbido",
      "Apego Ansioso",
      "Abusos sexuales",
      "Disforia de género",
    ],
  },
  online: {
    nombre: "Terapia Online",
    precio: "65€",
    duracion: "55 minutos",
    link: "/psicologo-online/",
    icon: OnlineIcon,
    target: "Adultos y Adolescentes",
    descripcion:
      "La terapia online es adecuada si quieres realizar terapia por videollamada. Es igual de eficaz que la presencial y se pueden combinar.",
    problemas: [
      "Ansiedad",
      "Depresión o Tristeza",
      "Autoestima",
      "Miedos",
      "Estrés",
      "Duelos",
      "Gestión de emociones",
      "Trauma",
      "Crecimiento personal",
      "Mobbing (Acoso Laboral)",
      "Burnout",
      "Ansiedad Social",
      "Dudas patológicas",
      "Crisis",
      "Timidez",
      "Toma de decisiones",
      "Fobias",
      "Ataques de pánico",
      "Inseguridades",
      "Ansiedad Social",
      "Crecimiento personal",
      "Autoconocimiento",
      "Habilidades Sociales",
      "Obsesiones",
      "Autolesiones",
      "Intentos de suicidio",
      "Rituales",
      "Rumiación",
      "Ataques de pánico",
      "Ataques de ansiedad",
      "Compulsiones",
      "Agorafobia",
      "Hipocondría",
      "TOC, TAG, TLP",
      "Trastornos de personalidad",
      "Problemas de alimentación",
      "Mobbing, Burnout, Bullying",
      "Imagen corporal",
      "Sexualidad",
      "Dismorfia corporal",
      "Baja líbido",
      "Apego Ansioso",
      "Abusos sexuales",
      "Disforia de género",
    ],
  },
  parejas: {
    nombre: "Terapia de Parejas/Familia",
    precio: "95€",
    duracion: "1 hora y 20 minutos",
    link: "/terapia-de-parejas-barcelona/",
    icon: ParejaIcon,
    target: "Parejas y Familias",
    descripcion:
      "La terapia de parejas y familias es adecuada para quienes estén atravesando alguna situación complicada en la vida familiar o de pareja.",
    problemas: [
      "Infidelidades",
      "Rupturas",
      "Celos",
      "Mentiras",
      "Relación tóxica",
      "Dependencia emocional",
      "Mala comunicación",
      "Maternidad / Paternidad",
      "Crianza",
      "Familia",
      "Crisis",
      "Segundas oportunidades",
      "Gestión de límites",
      "Gestión de conflictos",
      "Traiciones",
      "Problemas familiares",
      "Fertilidad",
      "Pérdidas",
      "Duelos",
      "Divorcios",
      "Hijos",
      "Relaciones abiertas",
      "Sexualidad",
      "Anorgasmia",
      "Eyaculación precoz",
      "Inseguridad, control",
    ],
  },
  psiconutricion: {
    nombre: "Psico-Nutrición",
    precio: "70€",
    duracion: "55 minutos",
    link: "/psiconutricion-barcelona/",
    icon: PsiconutricionIcon,
    target: "Adultos y Adolescentes",
    descripcion:
      "Realizamos terapia psicológica acompañada de un asesoramiento nutricional personalizado para mejorar la relación alimentaria de forma integral.",
    problemas: [
      "TCA",
      "Hambre emocional",
      "Restricción",
      "Compensación",
      "Culpa al comer",
      "Autoestima Corporal",
      "Atracones",
      "Anorexia",
      "Bulímia",
      "Vómitos",
      "Nutrición Clínica",
      "Trastornos Alimentarios",
      "Fagofobia",
      "Imagen corporal",
      "Sentimiento de culpa",
      "Alimentación Consciente",
      "Trastorno por atracón",
      "Vigorexia",
      "Pérdida de peso",
      "Obesidad",
      "Psiconutrición",
      "Alimentación Intuitiva",
      "Ortorexia",
      "Alimentación compulsiva",
      "Obsesión por el peso",
      "Pica",
      "Evitación de alimentos",
      "Autoconcepto",
      "Dismorfia corporal",
      "Relación alimentaria",
      "Vómitos",
      "Dietas",
      "Estrés y alimentación",
      "Autoconocimiento",
      "Cambio de hábitos",
    ],
  },
  nutricionClinica: {
    nombre: "Nutrición Clínica",
    precio: "65€",
    duracion: "55 minutos",
    link: "/nutricion-clinica",
    icon: PsiconutricionIcon,
    target: "Adultos y Adolescentes",
    descripcion:
      "Realizamos terapia psicológica acompañada de un asesoramiento nutricional personalizado para mejorar la relación alimentaria de forma integral.",
    problemas: [
      "Problemas hormonales",
      "Disfagias",
      "Gastritis",
      
    ],
  },
}
