version: '3'

services:
  site:
    build:
      dockerfile: Dockerfile
    command: jekyll serve --verbose --force_polling
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
