version: '3'

services:
  site:
    build:
      dockerfile: Dockerfile
      context: .
    command: jekyll serve --watch --force_polling --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
      - /srv/jekyll/new-site/ # ignore new site folder
    restart: always
