version: '3'

services:
  site:
    build:
      dockerfile: Dockerfile
    command: jekyll serve --watch --force_polling --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    restart: always
