#-------------------------------
# Lo que sale en Google:
title: Núria León, Psicóloga en Barcelona - Sesiones Online 45€ y Presencial 55€
logo: logo.svg
description: ¡Hola! Soy Núria León, Psicóloga en Barcelona y colegiada 26792. Hago sesiones Online 45€ y Presenciales 55€ en Español y Catalán.
keywords: nuria, leon, psicologa, barcelona, barcelona centro, psicologo en barcelona, psicologo online, psicologo presencial barcelona, terapia

#-------------------------------
# Lo que sale en el inicio:
author:
  name: Núria León
  image: hero.webp
  say-hello: Núria León, Psicóloga
  bio: ¡Hola! Soy Núria León, Psicóloga en Barcelona y Colegiada Número 26792. Hago sesiones Online y Presenciales en Barcelona en Español y Catalán. Psicóloga experta en autoestima, gestión emocional y relaciones.

#-------------------------------
# Contact links
gmaps: https://g.page/r/Cbk285IdPtR5EAg
twitter: nurialeonpsico
instagram: nurialeonpsicologa
youtube: UCqJfTv6FpCxw-HNjLHI_LNQ
linkedin: nurialeonsallent
facebook: nurialeonpsicologa
email: psicologa@nurialeon.com
phone: +34 650 011 672
location: Calle Castillejos 326, 1-1, Barcelona

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: nurialeonpsicologa # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: UA-111742878-3

#-------------------------------
# Newsletter
mailchimp: asd # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
