#-------------------------------
# General Site Settings
title: Núria León - Psicóloga Barcelona
logo: logo.svg
description: ¡Hola! Mi nombre es Núria León, soy psicóloga en Barcelona y colegiada número 26792. Desde hace mucho tiempo me dedico a ayudar a otras personas a superar dificultades y a sentirse mejor con sus vidas. ¿Quieres saber más?"
keywords: nuria, leon, psicologa, barcelona, online

#-------------------------------
# Author Settings
author:
  name: Núria León
  image: hero.jpg
  say-hello: Núria León, Psicóloga
  bio: ¡Hola! ¿Qué tal? Mi nombre es Núria León Sallent y soy psicóloga en Barcelona. Desde hace mucho tiempo que me dedico a ayudar a otras personas a superar dificultades y a sentirse mejor con sus vidas.

#-------------------------------
# Contact links
twitter: nurialeonpsico
instagram: nurialeonpsicologa
youtube: UCqJfTv6FpCxw-HNjLHI_LNQ
linkedin: nurialeonsallent
facebook: nurialeonpsicologa
email: psicologa@nurialeon.com
phone: +34 650 011 672

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: nurialeonpsicologa # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: UA-111742878-3

#-------------------------------
# Newsletter
mailchimp: asd # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
