#-------------------------------
# Lo que sale en Google:
title: Centro Núria León - Psicología y Terapia en Barcelona - Sesion Presencial 65€ y Online 55€
logo: logo.svg
description: Centro Núria León, Psicología y Terapia - Sesiones de Psicología Presenciales en Barcelona por 65€ y Sesiones Online por 55€.
keywords: nuria, leon, psicologa, barcelona, barcelona centro, psicologo en barcelona, psicologo online, psicologo presencial barcelona, terapia

#-------------------------------
# Lo que sale en el inicio:
author:
  name: Núria León
  image: hero.webp
  say-hello: Núria León, Psicóloga
  bio: ¡Hola! Soy Núria León, Psicóloga en Barcelona y Colegiada Número 26792. Hago sesiones Online y Presenciales en Barcelona en Español y Catalán. Psicóloga experta en autoestima, gestión emocional y relaciones.

#-------------------------------
# Contact links
gmaps: https://g.page/r/Cbk285IdPtR5EAg
twitter: nurialeonpsico
instagram: nurialeonpsicologa
youtube: UCqJfTv6FpCxw-HNjLHI_LNQ
linkedin: nurialeonsallent
facebook: nurialeonpsicologa
email: psicologa@nurialeon.com
phone: +34 650 011 672
location: Bailén 141, Esc. Izq. Entr. 6, 08037 Barcelona

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: nurialeonpsicologa # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: UA-111742878-3
google-gtag: G-PCWBZV5Z2N
